### ISSUE TITLE
undefined local variable or method `project' for ProjectImportService:Class Did you mean?  project

### ISSUE THREAD

**Issue by strangeman** [versioneye/ops_contrib#15]
Env:
Server:
- Docker version 1.12.4
- crawlj_worker:2.4.2
- rails_app:5.10.6
- rails_api:2.17.17
- crawlj:2.4.6
- tasks:2.10.0
- Bitbucket Server 4.8.5

Client:
-  Debian 8 + Chrome 55

I successfully connected to Bitbucket server via OAuth, got repos list and received repo metadata. But when I try to enable repo file (pom.xml in my case) - I got this errors:

```
application-50027d4….js:3 GET https://versioneye.ourdomain.com/user/projects/stash/ABC:ourproject::develop::pom.xml/import 500 (Internal Server Error)
send	@	application-50027d4….js:3
ajax	@	application-50027d4….js:3
(anonymous)	@	application_scm-84e1d5f….js:5

```

```
application_scm-84e1d5f….js:6 undefined local variable or method `project' for ProjectImportService:Class
Did you mean?  project
(anonymous)	@	application_scm-84e1d5f….js:6
c	@	application-50027d4….js:2
fireWith	@	application-50027d4….js:2
r	@	application-50027d4….js:3
(anonymous)	@	application-50027d4….js:3

```
![2016-12-26-203333_1366x768_scrot](https://cloud.githubusercontent.com/assets/1083576/21480683/1f4ea5e2-cbab-11e6-8d5b-8cdec16be364.png)

enterprise_worker.log:
```
ESC[0;37m2016-12-26 10:33:14.726ESC[0m [ESC[31mwtfESC[0m] /usr/local/bundle/bundler/gems/versioneye-core-937721cde521/lib/versioneye/services/project_import_service.rb:192:in `import_from_stash'
/usr/local/bundle/bundler/gems/versioneye-core-937721cde521/lib/versioneye/workers/git_repo_file_import_worker.rb:56:in `import'
/usr/local/bundle/bundler/gems/versioneye-core-937721cde521/lib/versioneye/workers/git_repo_file_import_worker.rb:20:in `block in work'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/consumer.rb:56:in `call'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/channel.rb:1705:in `block in handle_frameset'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/consumer_work_pool.rb:107:in `block (2 levels) in run_loop'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/consumer_work_pool.rb:102:in `loop'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/consumer_work_pool.rb:102:in `block in run_loop'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/consumer_work_pool.rb:101:in `catch'
/usr/local/bundle/gems/bunny-2.6.1/lib/bunny/consumer_work_pool.rb:101:in `run_loop' (pid:64)
ESC[0;37m2016-12-26 10:33:14.726ESC[0m [ESC[32mfyiESC[0m]  [x] GitRepoFileImportWorker job done stash:::amarkelov:::ABC/ourproject:::pom.xml:::develop:::58609f55e55ad00011898310 (pid:64)

```

enterprise_app.log:
```
I, [2016-12-26T10:33:31.652884 #12]  INFO -- : Started GET "/user/projects/stash/ABC:ourproject::develop::pom.xml/import" for MY_IP at 2016-12-26 10:33:31 +0000
I, [2016-12-26T10:33:31.653509 #12]  INFO -- : Processing by User::StashReposController#import as JSON
I, [2016-12-26T10:33:31.653538 #12]  INFO -- :   Parameters: {"id"=>"ABC:ourproject::develop::pom.xml"}
I, [2016-12-26T10:33:31.657111 #12]  INFO -- :   Rendering text template
I, [2016-12-26T10:33:31.657166 #12]  INFO -- :   Rendered text template (0.0ms)
I, [2016-12-26T10:33:31.657310 #12]  INFO -- : Completed 500 Internal Server Error in 4ms (Views: 0.3ms)

```

**Comment by reiz** [comment]
Hi @strangeman Can you please run `./versioneye-update` again and try it with the current Docker images? The problem looks familiar and I guess I solved it already some time ago. If the problem still exists after the update we can schedule a screen sharing session.

**Comment by strangeman** [comment]
I updated images and added crawlr image. Still got the same error. :(

**Comment by reiz** [comment]
@strangeman Hm, that's Odd. Let's schedule a screen sharing session. Send me an email to reiz [at] versioneye.com with time you are available. I'm in the Berlin timezone.

**Comment by reiz** [comment]
I close this ticket. Please contact me via email and let's schedule a screen sharing session to solve this.

**Comment by strangeman** [comment]
FYI, with latest versions of VersionEye and Bitbucket Server all working correctly :)

**Comment by reiz** [comment]
Awesome :-)
